services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
      platforms:
        - linux/amd64
      target: dev
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - ./models:/opt/models
      - ./main.py:/app/main.py
