print_summary: true
seed: 42

data:
  val_split: 0.1
  dataset: 'data/images/train'

model:
  seed: 42
  n_classes: 10
  input_shape: [256,256,3]
  hidden_layers:
    - activation: relu
      n_units: 300
    - activation: relu
      n_units: 300
  output_activation: softmax

train:
  # loss: sparse_categorical_crossentropy
  loss: categorical_crossentropy
  optimizer: Adam 
  optimizer_params: 
    learning_rate: 1e-4
    weight_decay: 5.0
  metrics: [accuracy, precision, recall, auc]
  batch_size: 32 
  train_args:
    epochs: 500 

output:
  logdir: tf_logs
